name: icecommercialpowertest
description: Ice commecial power

version: 1.0.5+6

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_snack_bar: ^0.2.1
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.3
  dio : ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  gap: ^2.0.0
  google_fonts: ^3.0.1
  iconly: ^1.0.1
  injector: ^2.0.0
  intl: ^0.17.0
  logger : ^1.1.0
  lottie: ^1.3.0
  pin_code_fields: ^7.4.0  
  provider: ^6.0.3
  sentry_flutter: ^6.6.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  
   
dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mockito: ^5.2.0
  bloc_test: ^9.1.0
  integration_test:
    sdk: flutter
  
dependency_overrides:
  analyzer: ^4.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/lotties/
   - assets/fonts/
  
  fonts:
    - family: Gordita
      fonts:
        - asset: assets/fonts/Gordita-Light.otf
          weight: 300
        - asset: assets/fonts/Gordita-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Gordita-Regular.otf
          weight: 400
        - asset: assets/fonts/Gordita-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Gordita-Medium.otf
          weight: 500
        - asset: assets/fonts/Gordita-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Gordita-Bold.otf
          weight: 700
        - asset: assets/fonts/Gordita-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Gordita-Black.otf
          weight: 900
        - asset: assets/fonts/Gordita-BlackItalic.otf
          weight: 900
          style: italic