// Mocks generated by Mockito 5.2.0 from annotations
// in icecommercialpowertest/test/repository/auth_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:icecommercialpowertest/domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeLoginResponseData_0 extends _i1.Fake
    implements _i2.LoginResponseData {}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.LoginResponseData> login(
          _i2.LoginRequestData? loginRequestData) =>
      (super.noSuchMethod(Invocation.method(#login, [loginRequestData]),
              returnValue: Future<_i2.LoginResponseData>.value(
                  _FakeLoginResponseData_0()))
          as _i3.Future<_i2.LoginResponseData>);
  @override
  _i3.Future<String> register(_i2.SignUpRequestData? registeRequestData) =>
      (super.noSuchMethod(Invocation.method(#register, [registeRequestData]),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<String> updateProfile(dynamic requestData) =>
      (super.noSuchMethod(Invocation.method(#updateProfile, [requestData]),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<dynamic> setUp() =>
      (super.noSuchMethod(Invocation.method(#setUp, []),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> getUser() =>
      (super.noSuchMethod(Invocation.method(#getUser, []),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
